# Generated by Django 2.2.4 on 2020-02-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='categories',
            new_name='category',
        ),
    ]
