# Generated by Django 2.2.4 on 2020-02-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200205_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='categories',
        ),
    ]
